# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\x06RPCPkg\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x06\x43oords\x12\x12\n\x06values\x18\x01 \x03(\x01\x42\x02\x10\x01\x32;\n\x03RPC\x12\x34\n\x08GetCoord\x12\x16.google.protobuf.Empty\x1a\x0e.RPCPkg.Coords\"\x00\x42\x0c\xaa\x02\tRPCClientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\tRPCClient'
  _COORDS.fields_by_name['values']._options = None
  _COORDS.fields_by_name['values']._serialized_options = b'\020\001'
  _COORDS._serialized_start=50
  _COORDS._serialized_end=78
  _RPC._serialized_start=80
  _RPC._serialized_end=139
# @@protoc_insertion_point(module_scope)
